expected_fields:
  - allowed_address_pairs
  - binding_host_id
  - binding_profile
  - binding_vif_details
  - binding_vif_type
  - binding_vnic_type
  - created_at
  - data_plane_status
  - description
  - device_id
  - device_owner
  - device_profile
  - dns_assignment
  - dns_domain
  - dns_name
  - extra_dhcp_opts
  - fixed_ips
  - id
  - ip_allocation
  - is_admin_state_up
  - is_port_security_enabled
  - mac_address
  - name
  - network_id
  - numa_affinity_policy
  - project_id
  - propagate_uplink_status
  - qos_network_policy_id
  - qos_policy_id
  - resource_request
  - revision_number
  - security_group_ids
  - status
  - tags
  - tenant_id
  - trunk_details
  - updated_at
network_name: ansible_port_network
no_security_groups: True
port_name: ansible_port
subnet_name: ansible_port_subnet
