---
- name: Create trait
  openstack.cloud.trait:
    cloud: "{{ cloud }}"
    state: present
    id: "{{ trait_name }}"
  until: result is success
  retries: 5
  delay: 20
  register: result

- name: Assert trait
  assert:
    that:
      - "'name' in result.trait"
      - "result.trait.id == trait_name"

- name: Remove trait
  openstack.cloud.trait:
    cloud: "{{ cloud }}"
    state: absent
    id: "{{ trait_name }}"
  register: result1

- name: Assert trait removed
  assert:
    that:
      - "'trait' not in result1"
